travis:
  secure:
    BINSTAR_TOKEN: ojGK+CIxEfzWjFJskIa9JxBfIGr9tL1+xeTorEcYxmCnRhA4gQQnMnTYOT0eg/56IMukC90xfNtQ7sjmHxCnHVNVEOeJVPPF58hT3dqg3El34bX96nGXxG/0hsRSdbKgpaQcTWTtyMAR4QsKEKGoV5NopDh5WKpYe0qUdLJEkCLjiAU1/F7Srk+Lv/X5JEl1/QZddWV5lt7h/3EhAT4FZyNWIC1Is3x3As5D1R+Pumuc+XQ1GzgG12aVBGOQZxbh/BJLc7D9ASFnmwqwuFvOiyvhxv9XSnEV9TakymmLV6kqiMQSOcFasyHKX+RFBGtvKh6wE8oDsWQOGRslbgdo6gtzD8+T+Q2gkoIDTC3Q4+sdUdUbe7UiYg0bsgc70E3yoEjwtNyIR7gacVMYvQiPVFJJf3TqzncEgv4EI6Zo6yrdwl41M/kF0dFdM7dSswIO/ofZk2AZlWNkaNAHNRy1+MN/o6jBX8KotxVcsuId/pmQxbFKMcUNbU8APpF1TKHmgVlNKFCsR/jq/lTPWA58Y7mN3EK1Wovr0bg11iudQjFSce58o1WmGXQ5AdM/TNbuoSDX3jLsqdqv5iwH/Pwqwgu02s0biDCiGR5zY/jLkgTlJ7vVf71qsQ10d0kIpbutte0nrlczp+1FtBNGg7+soR1l35955II8XRxIBXBLV+s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
