travis:
  secure:
    BINSTAR_TOKEN: X0ni5rcyCJyCRNxSR+seqNAQFxSsSCxK5POvFQUHtndWyXEJjNpE2QG61L1MwWNnhxcTf+VP7dPOUr0oGc5WpKkU8+tTh4VHZw++VgW7wSxCvP74+U+5MTQLppwHxGfNXJkNb8vMPPfgmxiRWS+V5p5r3HUuPKLRjhT2gxLlU8LXCZ+lPpOE9xsNZc+1wkOd2bJAhtq1bEkRrAKL6q0ccIDiM72Fu039MClWHtF/BUtJq4qOPCFC5R8HKeGrG0mIxSPOG22rc3zwH6bjmgxK0MM/DXqCK0SkoLVwRmtELF6EmNZefzsXJUxacjwkEFoMNgHqyV70wJq1xsK14BJlew43GQEofCp+esF3E5w+o5DexYmajIMAUulPcPXhWWZfuQ+cF6Oc3FLVD0gdYgO2AUOw+cUpFUr8yrrZV4PPjuavrGA4R4sWakLpQb4cm10NxLI90ABm2I8zjUs3dd60EpJo5nhulGJ+ssSs+vkK469GO1I7UUVDvzQ+z9sbhGoSK12iuU34tLXHUZZuDPXFroFjDxGsp+5+3kpyAETnfroC73ga83TTQF3jrOt+1Ir1BSwW5Zekp6VcFShq1F6lddSzlx6BFbKvgunj1z5XKlEZWUQpEw3jYMpndqZkYtDrNONzX0qMBXxsQPFkMuUahqxP83UjNfO1ZzgOCgVMqNU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
